-- ============================================================================
-- Findlay Events — sample data (optional)
-- Run AFTER schema.sql. Inserts the same demo events + garage sales the
-- prototype ships with, already 'approved' so they show immediately.
-- Times are US Eastern (-04:00 = EDT). Safe to delete these rows later.
-- ============================================================================

insert into public.events
  (city_id, title, category, emoji, start_at, end_at, venue, address, price, host, featured, description, status)
values
  ('findlay','Riverside Park Summer Concert','Music','🎶','2026-06-19T19:00:00-04:00','2026-06-19T21:00:00-04:00','Riverside Park Amphitheater','231 McManness Ave, Findlay, OH','Free','Findlay Parks & Recreation',true,'Bring a lawn chair or blanket and enjoy a free evening of live music by the river. Local food trucks on site. Family friendly and open to all ages.','approved'),
  ('findlay','Downtown Findlay Farmers Market','Market','🥕','2026-06-20T09:00:00-04:00','2026-06-20T13:00:00-04:00','Saturday Market on Main','S Main St, Downtown Findlay, OH','Free entry','Findlay Downtown Business Association',true,'Fresh local produce, baked goods, handmade crafts, and flowers from Hancock County growers and makers. Every Saturday morning through October.','approved'),
  ('findlay','Family Story Time at the Library','Family','📚','2026-06-17T10:30:00-04:00','2026-06-17T11:15:00-04:00','Findlay-Hancock County Public Library','206 Broadway St, Findlay, OH','Free','Findlay-Hancock County Public Library',false,'A gentle morning of stories, songs, and rhymes for young children and their grown-ups. No registration needed.','approved'),
  ('findlay','Marathon Center: An Evening of Jazz','Arts','🎷','2026-06-21T19:30:00-04:00','2026-06-21T21:30:00-04:00','Marathon Center for the Performing Arts','200 W Main Cross St, Findlay, OH','$25 - $40','Marathon Center for the Performing Arts',true,'An intimate evening of classic and contemporary jazz in Findlay''s premier performance hall. Reserved seating; doors open 30 minutes early.','approved'),
  ('findlay','Hancock County Fair Kickoff','Community','🎡','2026-06-27T10:00:00-04:00','2026-06-27T22:00:00-04:00','Hancock County Fairgrounds','1017 E Sandusky St, Findlay, OH','$8 / kids under 5 free','Hancock County Agricultural Society',false,'Rides, livestock shows, fair food, and live entertainment kick off the annual county fair. Fun for the whole family.','approved'),
  ('findlay','Dietsch Brothers Ice Cream Social','Food','🍦','2026-06-22T15:00:00-04:00','2026-06-22T18:00:00-04:00','Dietsch Brothers Fine Chocolates & Ice Cream','400 W Main Cross St, Findlay, OH','Pay per item','Dietsch Brothers',false,'A Findlay tradition since 1937. Stop in for hand-dipped ice cream and homemade chocolates on a summer afternoon.','approved'),
  ('findlay','Flag City Balloon Fest Planning Walk','Community','🎈','2026-06-24T18:00:00-04:00','2026-06-24T19:30:00-04:00','Emory Adams Park','1212 Lima Ave, Findlay, OH','Free','Flag City Balloon Fest Committee',false,'Volunteers and curious neighbors welcome. Learn how the annual hot air balloon festival comes together and how you can help.','approved'),
  ('findlay','Pickleball Open Play','Sports','🏓','2026-06-18T08:00:00-04:00','2026-06-18T10:00:00-04:00','Riverbend Recreation Area','16618 Township Rd 208, Findlay, OH','$3 drop-in','Findlay Pickleball Club',false,'All skill levels welcome, including beginners. Paddles available to borrow. A friendly, social morning of pickleball.','approved'),
  ('findlay','Beginner Smartphone Help Session','Education','📱','2026-06-23T13:00:00-04:00','2026-06-23T14:30:00-04:00','Findlay-Hancock County Public Library','206 Broadway St, Findlay, OH','Free','Library Tech Help Desk',false,'Friendly one-on-one help with your phone or tablet. Learn texting, photos, video calls, and apps at your own pace. No question is too small.','approved'),
  ('findlay','Sunrise Yoga in the Park','Sports','🧘','2026-06-21T07:30:00-04:00','2026-06-21T08:30:00-04:00','Riverside Park','231 McManness Ave, Findlay, OH','$5 suggested','Findlay Community Yoga',false,'Gentle, all-levels outdoor yoga to start your weekend. Bring your own mat. Modifications offered for every pose.','approved'),
  ('findlay','Historic Downtown Walking Tour','Education','🏛️','2026-06-26T17:30:00-04:00','2026-06-26T19:00:00-04:00','Hancock Historical Museum','422 W Sandusky St, Findlay, OH','$10','Hancock Historical Museum',false,'A guided stroll through Findlay''s historic downtown with stories of the oil boom era and the city''s architecture.','approved'),
  ('findlay','Food Truck Friday','Food','🌮','2026-06-26T11:00:00-04:00','2026-06-26T14:00:00-04:00','Dorney Plaza / City Building','318 Dorney Plaza, Findlay, OH','Pay per item','Downtown Findlay Inc.',false,'A rotating lineup of local food trucks serving lunch downtown. A great midday break with plenty of seating.','approved'),
  ('tiffin','Tiffin Art Walk','Arts','🎨','2026-06-20T17:00:00-04:00','2026-06-20T20:00:00-04:00','Downtown Tiffin','S Washington St, Tiffin, OH','Free','Tiffin Art Guild',true,'Galleries, pop-up artists, and live music fill downtown Tiffin for a relaxed evening art walk.','approved'),
  ('bowling-green','BG Summer Farmers Market','Market','🍅','2026-06-17T08:00:00-04:00','2026-06-17T12:00:00-04:00','Wood County Courthouse Square','1 Courthouse Sq, Bowling Green, OH','Free entry','BG Farmers Market',true,'Wednesday morning market with local produce, meats, honey, and handmade goods on the courthouse lawn.','approved');

insert into public.garage_sales
  (city_id, title, type, start_date, end_date, daily_start, daily_end, address, neighborhood, items, host, note, status)
values
  ('findlay','Big Multi-Family Garage Sale','Multi-Family Sale','2026-06-19','2026-06-20','8:00 AM','3:00 PM','1224 Western Ave, Findlay, OH','Western Avenue','{Furniture,"Kids & Baby",Toys,Household}','The Miller Family','Early birds welcome. Cash only. Three families combining — lots of kids'' items and a like-new sofa.','approved'),
  ('findlay','Estate Sale — Everything Priced to Sell','Estate Sale','2026-06-20','2026-06-20','9:00 AM','2:00 PM','512 Country Club Dr, Findlay, OH','Country Club','{Antiques,Furniture,Jewelry,Household}','Hancock Estate Services','Antique dining set, vintage glassware, costume jewelry, and quality furniture. Numbers handed out at 8:30 AM.','approved'),
  ('findlay','Moving Sale — Must Go This Weekend!','Moving Sale','2026-06-26','2026-06-28','8:00 AM','5:00 PM','845 Larkins St, Findlay, OH','Larkins Street','{Furniture,Electronics,Tools,Garden}','The Reyes Family','Relocating out of state — everything must go. TV, power tools, patio set, washer & dryer. Make an offer!','approved'),
  ('findlay','Church Rummage & Bake Sale','Rummage Sale','2026-06-20','2026-06-20','8:00 AM','1:00 PM','201 W Sandusky St, Findlay, OH','Downtown','{Clothing,Books,Household,Toys}','First Presbyterian Church','Fill-a-bag for $5 in the last hour. Homemade baked goods, gently used clothing, books, and housewares.','approved'),
  ('findlay','Whole-Street Neighborhood Sale','Yard Sale','2026-06-27','2026-06-27','8:00 AM','2:00 PM','Bright Rd & Sunset Dr, Findlay, OH','Bright Road','{Furniture,Clothing,Toys,"Sporting Goods",Garden}','Bright Road Neighbors','Over a dozen homes participating up and down the street. Maps available at the corner. Something for everyone!','approved'),
  ('findlay','Garage & Tool Cleanout','Garage Sale','2026-06-21','2026-06-21','7:30 AM','12:00 PM','418 Lincoln St, Findlay, OH','Lincoln Street','{Tools,"Sporting Goods",Electronics}','Dave K.','Hand tools, power tools, fishing gear, and golf clubs. No early birds please.','approved'),
  ('tiffin','Front Yard Sale','Yard Sale','2026-06-20','2026-06-21','9:00 AM','4:00 PM','233 Miami St, Tiffin, OH','Miami Street','{Clothing,Books,Household}','The Johnson Family','Lots of women''s clothing, paperbacks, and kitchen items.','approved');

insert into public.food_trucks
  (city_id, name, cuisine, date, start_time, end_time, location_name, address, host, note, status)
values
  ('findlay','Flag City Tacos','Tacos','2026-06-18','11:00 AM','2:00 PM','Marathon Petroleum HQ Lot','539 S Main St, Findlay, OH','Flag City Tacos','Street tacos, burritos, and fresh-made guac. Lunch rush — order ahead by phone to skip the line.','approved'),
  ('findlay','Smokin'' Hancock BBQ','BBQ','2026-06-19','5:00 PM','8:00 PM','Riverside Park','231 McManness Ave, Findlay, OH','Smokin'' Hancock BBQ','Slow-smoked brisket, pulled pork, and ribs. Parked by the amphitheater before the summer concert.','approved'),
  ('findlay','The Rolling Scoop','Ice Cream','2026-06-20','1:00 PM','6:00 PM','Dorney Plaza','318 Dorney Plaza, Findlay, OH','The Rolling Scoop','Hand-dipped cones, sundaes, and dairy-free options. Find us downtown all afternoon.','approved'),
  ('findlay','Bean There Coffee Truck','Coffee','2026-06-17','7:00 AM','11:00 AM','Findlay Village Mall','1800 Tiffin Ave, Findlay, OH','Bean There','Espresso, cold brew, and fresh muffins to start your morning.','approved'),
  ('findlay','Buckeye Burgers','Burgers','2026-06-21','11:30 AM','2:30 PM','Emory Adams Park','1212 Lima Ave, Findlay, OH','Buckeye Burgers','Smash burgers, hand-cut fries, and milkshakes. Cash and cards welcome.','approved'),
  ('findlay','Pho Sho','Asian','2026-06-22','5:00 PM','8:00 PM','University of Findlay — Main Lot','1000 N Main St, Findlay, OH','Pho Sho','Vietnamese pho, banh mi, and spring rolls. Vegetarian options available.','approved'),
  ('tiffin','Seneca Street Eats','Sandwiches','2026-06-20','11:00 AM','2:00 PM','Downtown Tiffin','S Washington St, Tiffin, OH','Seneca Street Eats','Gourmet grilled cheese and soups. Parked near the courthouse.','approved');
